name: Run Scheduling Algorithm

on:
  push:
    branches:
      - master  # Assume the file is pushed to the master branch for simplicity

permissions:
  contents: write  # Grant write access to repository contents

jobs:
  run_schedule:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Find the uploaded file
      id: find_file
      run: |
        FILE=$(find . -name "*.xlsx" | head -n 1)
        echo "FILE_PATH=$FILE" >> $GITHUB_ENV

    - name: Run scheduling script using the uploaded file
      run: python main.py ${{ env.FILE_PATH }}

    - name: Configure Git
      run: |
        git config --local user.email "github-actions@github.com"
        git config --local user.name "GitHub Actions"

    - name: Commit and Push the Generated File
      run: |
        git add Export.xlsx
        git commit -m "Add generated Export.xlsx to root directory"
        git push origin master  # Push to the master branch

    - name: Verify file exists
      run: ls -la Export.xlsx
