name: Run Scheduling Algorithm

on:
  push:
    paths:
      - 'Input.xlsx'  # Trigger when Input.xlsx is added or modified

jobs:
  run_schedule:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run scheduling script
      run: python main.py "Input.xlsx"

    - name: Configure Git (local)
      run: |
        git config user.email "github-actions@example.com"
        git config user.name "GitHub Actions"

    - name: Commit and Push the New Generated File
      run: |
        git add Export.xlsx
        git commit -m "Add new generated Export.xlsx"
        git push origin master

    - name: Wait before deleting files
      run: sleep 60  # Wait for a short time before deleting the files

    - name: Delete Input.xlsx and Export.xlsx
      run: |
        if [ -f Input.xlsx ]; then
          rm Input.xlsx
        fi
        if [ -f Export.xlsx ]; then
          rm Export.xlsx
        fi

    - name: Commit Deletion
      run: |
        git add -u
        git commit -m "Delete Input.xlsx and Export.xlsx after processing"
        git push origin master
