name: Run Scheduling Algorithm

on:
  push:
    branches:
      - uploads  # The branch where the user-uploaded file is pushed

jobs:
  run_schedule:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run scheduling script
      run: python main.py path-to-uploaded-file.xlsx

    - name: Commit and Push the Generated File
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git checkout -b gh-pages
        mv Export.xlsx Export.xlsx  # Move it to the root directory
        git add Export.xlsx
        git commit -m "Add generated Export.xlsx"
        git push origin gh-pages --force  # Force push to update gh-pages
